### ISSUE TITLE
Cannot find module 'socket.io'

### ISSUE THREAD

**Issue by hthetiot** [networked-aframe/naf-easyrtc-adapter#3]
npm run start result in Cannot find module 'socket.io' 

>  npm run start

> naf-easyrtc-adapter@0.1.0 start naf-easyrtc-adapter
> cross-env NODE_ENV=production node ./server/index.js
> module.js:549
>     throw err;
>     ^
> 
> Error: Cannot find module 'socket.io'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (naf-easyrtc-adapter/server/index.js:5:16)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)

**Comment by hthetiot** [comment]
Fixed by 2cc35b0c3811d77700f5cf40097aaf7bda3b492c in #1

**Comment by vincentfretin** [comment]
The easyrtc adapter moved again to the networked-aframe repository. I'm closing all issues in this repository.
