### ISSUE TITLE
dist/naf-easyrtc-adapter.js 404 (Not Found)

### ISSUE THREAD

**Issue by hthetiot** [networked-aframe/naf-easyrtc-adapter#4]
npm run start result in 404 on `dist/naf-easyrtc-adapter.js`

<img width="1259" alt="Screen Shot 2020-02-08 at 3 41 18 PM" src="https://user-images.githubusercontent.com/8635/74087176-1bc41900-4a8a-11ea-8687-ecf7ba2bd1d9.png">

**Comment by hthetiot** [comment]
Fix by aed2ce6f02519fc97b87b442782de072d5715e77 in #1

**Comment by vincentfretin** [comment]
The easyrtc adapter moved again to the networked-aframe repository. I'm closing all issues in this repository.
