### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setSocketUrl' of undefined

### ISSUE THREAD

**Issue by hthetiot** [networked-aframe/naf-easyrtc-adapter#5]
Easyrtc and Sockiet.io-client is not loaded by the example.

<img width="1259" alt="Screen Shot 2020-02-08 at 3 41 18 PM" src="https://user-images.githubusercontent.com/8635/74087169-0d75fd00-4a8a-11ea-8607-d3986a7132a3.png">

**Comment by hthetiot** [comment]
Fixed by https://github.com/networked-aframe/naf-easyrtc-adapter/pull/2/commits/2cc35b0c3811d77700f5cf40097aaf7bda3b492c#diff-5b0e3367cfabe5a0173e80753b827d6cR14

**Comment by vincentfretin** [comment]
The easyrtc adapter moved again to the networked-aframe repository. I'm closing all issues in this repository.
