### ISSUE TITLE
Cannot join session with microphone disabled

### ISSUE THREAD

**Issue by joesaxton** [networked-aframe/naf-easyrtc-adapter#7]
I believe this could be a similar to the issue at https://github.com/networked-aframe/networked-aframe/pull/201.

If the microphone is blocked, the user isn't detected in the logs, and can't connect to the room. However, if joining with microphone on, and then blocking, the user stays in room.

Any help with this would be greatly appreciated.

**Comment by vincentfretin** [comment]
The adapter moved again in the networked-aframe repository. I'm closing all issues from this repository.
See this issue too https://github.com/networked-aframe/networked-aframe/issues/55
